language: node_js
node_js:
  - node
notifications:
  email:
    recipients:
      - pru.mike@gmail.com
    on_success: always
    on_failure: always
sudo: false
after_success:
  - istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage

